apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway
  namespace: cyberdesk-system 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gateway-vnc-access
rules:
- apiGroups: ["subresources.kubevirt.io"]
  resources: ["virtualmachineinstances/vnc"]
  verbs: ["get"]
- apiGroups: [""] # Core API group
  resources: ["services"]
  verbs: ["get", "list", "watch"] # Add permissions to get service status
- apiGroups: [""]
  resources: ["services/status"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gateway-vnc-binding
  namespace: cyberdesk-system
subjects:
- kind: ServiceAccount
  name: gateway
  namespace: cyberdesk-system
roleRef:
  kind: ClusterRole
  name: gateway-vnc-access
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: cyberdesk-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      serviceAccountName: gateway
      containers:
      - name: gateway
        image: cyberdesk/gateway:v0.1.11
        envFrom:
        - secretRef:
            name: supabase-credentials
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: cyberdesk-system
spec:
  type: LoadBalancer
  selector:
    app: gateway
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http