apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway
  namespace: default 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gateway-vnc-access
rules:
- apiGroups: ["subresources.kubevirt.io"]
  resources: ["virtualmachineinstances/vnc"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gateway-vnc-binding
subjects:
- kind: ServiceAccount
  name: gateway
  namespace: default
roleRef:
  kind: ClusterRole
  name: gateway-vnc-access
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      serviceAccountName: gateway
      containers:
      - name: gateway
        image: cyberdesk/gateway:v0.1.5
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: LoadBalancer
  selector:
    app: gateway
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http