apiVersion: cyberdesk.io/v1alpha1
kind: StartCyberdeskOperator
metadata:
  # Name it 'bootstrap' or similar to indicate its purpose
  name: bootstrap-cyberdesk-setup 
  # Needs to be in the same namespace where the operator runs
  namespace: cyberdesk-system 
spec:
  # The spec can be empty for now, its existence triggers the handler
  {} 